[2023-02-07T09:09:28.406+0100] {__init__.py:50} DEBUG - Loading core task runner: StandardTaskRunner
[2023-02-07T09:09:28.417+0100] {taskinstance.py:1017} DEBUG - previous_execution_date was called
[2023-02-07T09:09:28.418+0100] {base_task_runner.py:69} DEBUG - Planning to run as the  user
[2023-02-07T09:09:28.420+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.get_author scheduled__2023-02-05T00:00:00+00:00 [queued]> from DB
[2023-02-07T09:09:28.427+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_author scheduled__2023-02-05T00:00:00+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2023-02-07T09:09:28.427+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_author scheduled__2023-02-05T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2023-02-07T09:09:28.427+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_author scheduled__2023-02-05T00:00:00+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2023-02-07T09:09:28.427+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_author scheduled__2023-02-05T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2023-02-07T09:09:28.432+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_author scheduled__2023-02-05T00:00:00+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2023-02-07T09:09:28.433+0100] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dagProcessusMetier.get_author scheduled__2023-02-05T00:00:00+00:00 [queued]>
[2023-02-07T09:09:28.433+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_author scheduled__2023-02-05T00:00:00+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2023-02-07T09:09:28.437+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_author scheduled__2023-02-05T00:00:00+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2023-02-07T09:09:28.437+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_author scheduled__2023-02-05T00:00:00+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2023-02-07T09:09:28.438+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_author scheduled__2023-02-05T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2023-02-07T09:09:28.439+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_author scheduled__2023-02-05T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2023-02-07T09:09:28.439+0100] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dagProcessusMetier.get_author scheduled__2023-02-05T00:00:00+00:00 [queued]>
[2023-02-07T09:09:28.439+0100] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-07T09:09:28.439+0100] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-02-07T09:09:28.439+0100] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-07T09:09:28.454+0100] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): get_author> on 2023-02-05 00:00:00+00:00
[2023-02-07T09:09:28.457+0100] {standard_task_runner.py:55} INFO - Started process 232 to run task
[2023-02-07T09:09:28.458+0100] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'dagProcessusMetier', 'get_author', 'scheduled__2023-02-05T00:00:00+00:00', '--job-id', '2563', '--raw', '--subdir', 'DAGS_FOLDER/dagProcessusMetier.py', '--cfg-path', '/tmp/tmpvmck1gm4']
[2023-02-07T09:09:28.459+0100] {standard_task_runner.py:83} INFO - Job 2563: Subtask get_author
[2023-02-07T09:09:28.459+0100] {cli_action_loggers.py:65} DEBUG - Calling callbacks: [<function default_action_log at 0x7f254a454790>]
[2023-02-07T09:09:28.470+0100] {settings.py:407} DEBUG - Disposing DB connection pool (PID 232)
[2023-02-07T09:09:28.470+0100] {settings.py:266} DEBUG - Setting up DB connection pool (PID 232)
[2023-02-07T09:09:28.470+0100] {settings.py:339} DEBUG - settings.prepare_engine_args(): Using NullPool
[2023-02-07T09:09:28.487+0100] {taskinstance.py:1017} DEBUG - previous_execution_date was called
[2023-02-07T09:09:28.489+0100] {task_command.py:388} INFO - Running <TaskInstance: dagProcessusMetier.get_author scheduled__2023-02-05T00:00:00+00:00 [running]> on host TR.
[2023-02-07T09:09:28.490+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.get_author scheduled__2023-02-05T00:00:00+00:00 [running]> from DB
[2023-02-07T09:09:28.507+0100] {taskinstance.py:1017} DEBUG - previous_execution_date was called
[2023-02-07T09:09:28.508+0100] {taskinstance.py:848} DEBUG - Clearing XCom data
[2023-02-07T09:09:28.531+0100] {retries.py:80} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2023-02-07T09:09:28.535+0100] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=thomas
AIRFLOW_CTX_DAG_ID=dagProcessusMetier
AIRFLOW_CTX_TASK_ID=get_author
AIRFLOW_CTX_EXECUTION_DATE=2023-02-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-05T00:00:00+00:00
[2023-02-07T09:09:28.535+0100] {__init__.py:117} DEBUG - Preparing lineage inlets and outlets
[2023-02-07T09:09:28.535+0100] {__init__.py:155} DEBUG - inlets: [], outlets: []
[2023-02-07T09:09:28.586+0100] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/tr/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/tr/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/tr/airflow/dags/dagProcessusMetier.py", line 91, in get_author
    twt_id = kwargs['twt_id']
KeyError: 'twt_id'
[2023-02-07T09:09:28.586+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.get_author scheduled__2023-02-05T00:00:00+00:00 [running]> from DB
[2023-02-07T09:09:28.590+0100] {taskinstance.py:2241} DEBUG - Task Duration set to 0.157002
[2023-02-07T09:09:28.590+0100] {taskinstance.py:1329} DEBUG - Clearing next_method and next_kwargs.
[2023-02-07T09:09:28.591+0100] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=dagProcessusMetier, task_id=get_author, execution_date=20230205T000000, start_date=20230207T080928, end_date=20230207T080928
[2023-02-07T09:09:28.603+0100] {cli_action_loggers.py:83} DEBUG - Calling callbacks: []
[2023-02-07T09:09:28.603+0100] {standard_task_runner.py:100} ERROR - Failed to execute job 2563 for task get_author ('twt_id'; 232)
[2023-02-07T09:09:28.632+0100] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-07T09:09:28.641+0100] {dagrun.py:688} DEBUG - number of tis tasks for <DagRun dagProcessusMetier @ 2023-02-05 00:00:00+00:00: scheduled__2023-02-05T00:00:00+00:00, state:running, queued_at: 2023-02-07 08:08:13.813279+00:00. externally triggered: False>: 0 task(s)
[2023-02-07T09:09:28.642+0100] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
