[2023-02-07T09:39:42.096+0100] {__init__.py:50} DEBUG - Loading core task runner: StandardTaskRunner
[2023-02-07T09:39:42.106+0100] {taskinstance.py:1017} DEBUG - previous_execution_date was called
[2023-02-07T09:39:42.108+0100] {base_task_runner.py:69} DEBUG - Planning to run as the  user
[2023-02-07T09:39:42.111+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.value manual__2023-02-07T08:38:33.165567+00:00 [queued]> from DB
[2023-02-07T09:39:42.125+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.value manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2023-02-07T09:39:42.125+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.value manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2023-02-07T09:39:42.125+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.value manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2023-02-07T09:39:42.125+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.value manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2023-02-07T09:39:42.125+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.value manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2023-02-07T09:39:42.125+0100] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dagProcessusMetier.value manual__2023-02-07T08:38:33.165567+00:00 [queued]>
[2023-02-07T09:39:42.128+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.value manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2023-02-07T09:39:42.130+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.value manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2023-02-07T09:39:42.130+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.value manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2023-02-07T09:39:42.130+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.value manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2023-02-07T09:39:42.130+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.value manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2023-02-07T09:39:42.132+0100] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dagProcessusMetier.value manual__2023-02-07T08:38:33.165567+00:00 [queued]>
[2023-02-07T09:39:42.132+0100] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-07T09:39:42.132+0100] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-02-07T09:39:42.132+0100] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-07T09:39:42.149+0100] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): value> on 2023-02-07 08:38:33.165567+00:00
[2023-02-07T09:39:42.153+0100] {standard_task_runner.py:55} INFO - Started process 2378 to run task
[2023-02-07T09:39:42.154+0100] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'dagProcessusMetier', 'value', 'manual__2023-02-07T08:38:33.165567+00:00', '--job-id', '2589', '--raw', '--subdir', 'DAGS_FOLDER/dagProcessusMetier.py', '--cfg-path', '/tmp/tmp_fve_h0s']
[2023-02-07T09:39:42.155+0100] {standard_task_runner.py:83} INFO - Job 2589: Subtask value
[2023-02-07T09:39:42.155+0100] {cli_action_loggers.py:65} DEBUG - Calling callbacks: [<function default_action_log at 0x7f2161960790>]
[2023-02-07T09:39:42.169+0100] {settings.py:407} DEBUG - Disposing DB connection pool (PID 2378)
[2023-02-07T09:39:42.169+0100] {settings.py:266} DEBUG - Setting up DB connection pool (PID 2378)
[2023-02-07T09:39:42.169+0100] {settings.py:339} DEBUG - settings.prepare_engine_args(): Using NullPool
[2023-02-07T09:39:42.191+0100] {taskinstance.py:1017} DEBUG - previous_execution_date was called
[2023-02-07T09:39:42.194+0100] {task_command.py:388} INFO - Running <TaskInstance: dagProcessusMetier.value manual__2023-02-07T08:38:33.165567+00:00 [running]> on host TR.
[2023-02-07T09:39:42.194+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.value manual__2023-02-07T08:38:33.165567+00:00 [running]> from DB
[2023-02-07T09:39:42.212+0100] {taskinstance.py:1017} DEBUG - previous_execution_date was called
[2023-02-07T09:39:42.214+0100] {taskinstance.py:848} DEBUG - Clearing XCom data
[2023-02-07T09:39:42.240+0100] {retries.py:80} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2023-02-07T09:39:42.245+0100] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=thomas
AIRFLOW_CTX_DAG_ID=dagProcessusMetier
AIRFLOW_CTX_TASK_ID=value
AIRFLOW_CTX_EXECUTION_DATE=2023-02-07T08:38:33.165567+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-07T08:38:33.165567+00:00
[2023-02-07T09:39:42.245+0100] {__init__.py:117} DEBUG - Preparing lineage inlets and outlets
[2023-02-07T09:39:42.245+0100] {__init__.py:155} DEBUG - inlets: [], outlets: []
[2023-02-07T09:39:42.245+0100] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/tr/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/tr/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/tr/airflow/dags/dagProcessusMetier.py", line 107, in value
    dict_list = kwargs['dict']
KeyError: 'dict'
[2023-02-07T09:39:42.246+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.value manual__2023-02-07T08:38:33.165567+00:00 [running]> from DB
[2023-02-07T09:39:42.248+0100] {taskinstance.py:2241} DEBUG - Task Duration set to 0.122868
[2023-02-07T09:39:42.249+0100] {taskinstance.py:1329} DEBUG - Clearing next_method and next_kwargs.
[2023-02-07T09:39:42.249+0100] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=dagProcessusMetier, task_id=value, execution_date=20230207T083833, start_date=20230207T083942, end_date=20230207T083942
[2023-02-07T09:39:42.262+0100] {cli_action_loggers.py:83} DEBUG - Calling callbacks: []
[2023-02-07T09:39:42.262+0100] {standard_task_runner.py:100} ERROR - Failed to execute job 2589 for task value ('dict'; 2378)
[2023-02-07T09:39:42.287+0100] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-07T09:39:42.300+0100] {dagrun.py:688} DEBUG - number of tis tasks for <DagRun dagProcessusMetier @ 2023-02-07 08:38:33.165567+00:00: manual__2023-02-07T08:38:33.165567+00:00, state:running, queued_at: 2023-02-07 08:38:33.178171+00:00. externally triggered: True>: 0 task(s)
[2023-02-07T09:39:42.300+0100] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
