[2023-02-07T09:10:35.085+0100] {__init__.py:50} DEBUG - Loading core task runner: StandardTaskRunner
[2023-02-07T09:10:35.096+0100] {taskinstance.py:1017} DEBUG - previous_execution_date was called
[2023-02-07T09:10:35.098+0100] {base_task_runner.py:69} DEBUG - Planning to run as the  user
[2023-02-07T09:10:35.100+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.get_all_tweet_ids scheduled__2023-02-06T00:00:00+00:00 [queued]> from DB
[2023-02-07T09:10:35.108+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_tweet_ids scheduled__2023-02-06T00:00:00+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2023-02-07T09:10:35.108+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_tweet_ids scheduled__2023-02-06T00:00:00+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2023-02-07T09:10:35.108+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_tweet_ids scheduled__2023-02-06T00:00:00+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2023-02-07T09:10:35.108+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_tweet_ids scheduled__2023-02-06T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2023-02-07T09:10:35.112+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_tweet_ids scheduled__2023-02-06T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2023-02-07T09:10:35.112+0100] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dagProcessusMetier.get_all_tweet_ids scheduled__2023-02-06T00:00:00+00:00 [queued]>
[2023-02-07T09:10:35.117+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_tweet_ids scheduled__2023-02-06T00:00:00+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2023-02-07T09:10:35.117+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_tweet_ids scheduled__2023-02-06T00:00:00+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2023-02-07T09:10:35.117+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_tweet_ids scheduled__2023-02-06T00:00:00+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2023-02-07T09:10:35.117+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_tweet_ids scheduled__2023-02-06T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2023-02-07T09:10:35.118+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_tweet_ids scheduled__2023-02-06T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2023-02-07T09:10:35.118+0100] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dagProcessusMetier.get_all_tweet_ids scheduled__2023-02-06T00:00:00+00:00 [queued]>
[2023-02-07T09:10:35.118+0100] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-07T09:10:35.118+0100] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-02-07T09:10:35.119+0100] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-07T09:10:35.134+0100] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): get_all_tweet_ids> on 2023-02-06 00:00:00+00:00
[2023-02-07T09:10:35.137+0100] {standard_task_runner.py:55} INFO - Started process 297 to run task
[2023-02-07T09:10:35.138+0100] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'dagProcessusMetier', 'get_all_tweet_ids', 'scheduled__2023-02-06T00:00:00+00:00', '--job-id', '2566', '--raw', '--subdir', 'DAGS_FOLDER/dagProcessusMetier.py', '--cfg-path', '/tmp/tmp9pegr96q']
[2023-02-07T09:10:35.139+0100] {standard_task_runner.py:83} INFO - Job 2566: Subtask get_all_tweet_ids
[2023-02-07T09:10:35.140+0100] {cli_action_loggers.py:65} DEBUG - Calling callbacks: [<function default_action_log at 0x7f7072a50790>]
[2023-02-07T09:10:35.151+0100] {settings.py:407} DEBUG - Disposing DB connection pool (PID 297)
[2023-02-07T09:10:35.152+0100] {settings.py:266} DEBUG - Setting up DB connection pool (PID 297)
[2023-02-07T09:10:35.152+0100] {settings.py:339} DEBUG - settings.prepare_engine_args(): Using NullPool
[2023-02-07T09:10:35.173+0100] {taskinstance.py:1017} DEBUG - previous_execution_date was called
[2023-02-07T09:10:35.174+0100] {task_command.py:388} INFO - Running <TaskInstance: dagProcessusMetier.get_all_tweet_ids scheduled__2023-02-06T00:00:00+00:00 [running]> on host TR.
[2023-02-07T09:10:35.175+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.get_all_tweet_ids scheduled__2023-02-06T00:00:00+00:00 [running]> from DB
[2023-02-07T09:10:35.194+0100] {taskinstance.py:1017} DEBUG - previous_execution_date was called
[2023-02-07T09:10:35.195+0100] {taskinstance.py:848} DEBUG - Clearing XCom data
[2023-02-07T09:10:35.222+0100] {retries.py:80} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2023-02-07T09:10:35.227+0100] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=thomas
AIRFLOW_CTX_DAG_ID=dagProcessusMetier
AIRFLOW_CTX_TASK_ID=get_all_tweet_ids
AIRFLOW_CTX_EXECUTION_DATE=2023-02-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-06T00:00:00+00:00
[2023-02-07T09:10:35.227+0100] {__init__.py:117} DEBUG - Preparing lineage inlets and outlets
[2023-02-07T09:10:35.227+0100] {__init__.py:155} DEBUG - inlets: [], outlets: []
[2023-02-07T09:10:40.161+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.get_all_tweet_ids scheduled__2023-02-06T00:00:00+00:00 [running]> from DB
[2023-02-07T09:10:40.166+0100] {base_job.py:240} DEBUG - [heartbeat]
[2023-02-07T09:10:45.212+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.get_all_tweet_ids scheduled__2023-02-06T00:00:00+00:00 [running]> from DB
[2023-02-07T09:10:45.215+0100] {base_job.py:240} DEBUG - [heartbeat]
[2023-02-07T09:10:50.249+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.get_all_tweet_ids scheduled__2023-02-06T00:00:00+00:00 [running]> from DB
[2023-02-07T09:10:50.252+0100] {base_job.py:240} DEBUG - [heartbeat]
[2023-02-07T09:10:55.275+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.get_all_tweet_ids scheduled__2023-02-06T00:00:00+00:00 [running]> from DB
[2023-02-07T09:10:55.278+0100] {base_job.py:240} DEBUG - [heartbeat]
[2023-02-07T09:11:00.318+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.get_all_tweet_ids scheduled__2023-02-06T00:00:00+00:00 [running]> from DB
[2023-02-07T09:11:00.321+0100] {base_job.py:240} DEBUG - [heartbeat]
[2023-02-07T09:11:05.348+0100] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/tr/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/tr/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/tr/airflow/dags/dagProcessusMetier.py", line 154, in get_all_tweet_ids
    for doc in docs:
  File "/home/tr/.local/lib/python3.10/site-packages/pymongo/cursor.py", line 1248, in next
    if len(self.__data) or self._refresh():
  File "/home/tr/.local/lib/python3.10/site-packages/pymongo/cursor.py", line 1139, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/tr/.local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1740, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/tr/.local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1685, in __start_session
    self._topology._check_implicit_session_support()
  File "/home/tr/.local/lib/python3.10/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/home/tr/.local/lib/python3.10/site-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/home/tr/.local/lib/python3.10/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: ac-7d3k6vb-shard-00-01.rs5oaul.mongodb.net:27017: timed out,ac-7d3k6vb-shard-00-02.rs5oaul.mongodb.net:27017: timed out,ac-7d3k6vb-shard-00-00.rs5oaul.mongodb.net:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 63e2077b51ca766f8ff2986b, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-7d3k6vb-shard-00-00.rs5oaul.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-7d3k6vb-shard-00-00.rs5oaul.mongodb.net:27017: timed out')>, <ServerDescription ('ac-7d3k6vb-shard-00-01.rs5oaul.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-7d3k6vb-shard-00-01.rs5oaul.mongodb.net:27017: timed out')>, <ServerDescription ('ac-7d3k6vb-shard-00-02.rs5oaul.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-7d3k6vb-shard-00-02.rs5oaul.mongodb.net:27017: timed out')>]>
[2023-02-07T09:11:05.349+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.get_all_tweet_ids scheduled__2023-02-06T00:00:00+00:00 [running]> from DB
[2023-02-07T09:11:05.352+0100] {taskinstance.py:2241} DEBUG - Task Duration set to 30.239863
[2023-02-07T09:11:05.353+0100] {taskinstance.py:1329} DEBUG - Clearing next_method and next_kwargs.
[2023-02-07T09:11:05.353+0100] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=dagProcessusMetier, task_id=get_all_tweet_ids, execution_date=20230206T000000, start_date=20230207T081035, end_date=20230207T081105
[2023-02-07T09:11:05.354+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.get_all_tweet_ids scheduled__2023-02-06T00:00:00+00:00 [running]> from DB
[2023-02-07T09:11:05.357+0100] {base_job.py:240} DEBUG - [heartbeat]
[2023-02-07T09:11:05.370+0100] {cli_action_loggers.py:83} DEBUG - Calling callbacks: []
[2023-02-07T09:11:05.371+0100] {standard_task_runner.py:100} ERROR - Failed to execute job 2566 for task get_all_tweet_ids (ac-7d3k6vb-shard-00-01.rs5oaul.mongodb.net:27017: timed out,ac-7d3k6vb-shard-00-02.rs5oaul.mongodb.net:27017: timed out,ac-7d3k6vb-shard-00-00.rs5oaul.mongodb.net:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 63e2077b51ca766f8ff2986b, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-7d3k6vb-shard-00-00.rs5oaul.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-7d3k6vb-shard-00-00.rs5oaul.mongodb.net:27017: timed out')>, <ServerDescription ('ac-7d3k6vb-shard-00-01.rs5oaul.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-7d3k6vb-shard-00-01.rs5oaul.mongodb.net:27017: timed out')>, <ServerDescription ('ac-7d3k6vb-shard-00-02.rs5oaul.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-7d3k6vb-shard-00-02.rs5oaul.mongodb.net:27017: timed out')>]>; 297)
[2023-02-07T09:11:05.384+0100] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-07T09:11:05.394+0100] {dagrun.py:688} DEBUG - number of tis tasks for <DagRun dagProcessusMetier @ 2023-02-06 00:00:00+00:00: scheduled__2023-02-06T00:00:00+00:00, state:running, queued_at: 2023-02-07 08:09:29.422883+00:00. externally triggered: False>: 0 task(s)
[2023-02-07T09:11:05.395+0100] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
