[2023-02-07T09:39:07.657+0100] {__init__.py:50} DEBUG - Loading core task runner: StandardTaskRunner
[2023-02-07T09:39:07.667+0100] {taskinstance.py:1017} DEBUG - previous_execution_date was called
[2023-02-07T09:39:07.669+0100] {base_task_runner.py:69} DEBUG - Planning to run as the  user
[2023-02-07T09:39:07.671+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.get_all_tweet_ids manual__2023-02-07T08:38:33.165567+00:00 [queued]> from DB
[2023-02-07T09:39:07.679+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_tweet_ids manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2023-02-07T09:39:07.679+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_tweet_ids manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2023-02-07T09:39:07.679+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_tweet_ids manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2023-02-07T09:39:07.679+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_tweet_ids manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2023-02-07T09:39:07.680+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_tweet_ids manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2023-02-07T09:39:07.683+0100] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dagProcessusMetier.get_all_tweet_ids manual__2023-02-07T08:38:33.165567+00:00 [queued]>
[2023-02-07T09:39:07.683+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_tweet_ids manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2023-02-07T09:39:07.683+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_tweet_ids manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2023-02-07T09:39:07.684+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_tweet_ids manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2023-02-07T09:39:07.688+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_tweet_ids manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2023-02-07T09:39:07.688+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.get_all_tweet_ids manual__2023-02-07T08:38:33.165567+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2023-02-07T09:39:07.689+0100] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dagProcessusMetier.get_all_tweet_ids manual__2023-02-07T08:38:33.165567+00:00 [queued]>
[2023-02-07T09:39:07.689+0100] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-07T09:39:07.689+0100] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-02-07T09:39:07.689+0100] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-07T09:39:07.707+0100] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): get_all_tweet_ids> on 2023-02-07 08:38:33.165567+00:00
[2023-02-07T09:39:07.709+0100] {standard_task_runner.py:55} INFO - Started process 2340 to run task
[2023-02-07T09:39:07.710+0100] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'dagProcessusMetier', 'get_all_tweet_ids', 'manual__2023-02-07T08:38:33.165567+00:00', '--job-id', '2587', '--raw', '--subdir', 'DAGS_FOLDER/dagProcessusMetier.py', '--cfg-path', '/tmp/tmprfnvarj3']
[2023-02-07T09:39:07.711+0100] {standard_task_runner.py:83} INFO - Job 2587: Subtask get_all_tweet_ids
[2023-02-07T09:39:07.712+0100] {cli_action_loggers.py:65} DEBUG - Calling callbacks: [<function default_action_log at 0x7f83bc554790>]
[2023-02-07T09:39:07.724+0100] {settings.py:407} DEBUG - Disposing DB connection pool (PID 2340)
[2023-02-07T09:39:07.725+0100] {settings.py:266} DEBUG - Setting up DB connection pool (PID 2340)
[2023-02-07T09:39:07.725+0100] {settings.py:339} DEBUG - settings.prepare_engine_args(): Using NullPool
[2023-02-07T09:39:07.745+0100] {taskinstance.py:1017} DEBUG - previous_execution_date was called
[2023-02-07T09:39:07.747+0100] {task_command.py:388} INFO - Running <TaskInstance: dagProcessusMetier.get_all_tweet_ids manual__2023-02-07T08:38:33.165567+00:00 [running]> on host TR.
[2023-02-07T09:39:07.747+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.get_all_tweet_ids manual__2023-02-07T08:38:33.165567+00:00 [running]> from DB
[2023-02-07T09:39:07.763+0100] {taskinstance.py:1017} DEBUG - previous_execution_date was called
[2023-02-07T09:39:07.764+0100] {taskinstance.py:848} DEBUG - Clearing XCom data
[2023-02-07T09:39:07.789+0100] {retries.py:80} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2023-02-07T09:39:07.793+0100] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=thomas
AIRFLOW_CTX_DAG_ID=dagProcessusMetier
AIRFLOW_CTX_TASK_ID=get_all_tweet_ids
AIRFLOW_CTX_EXECUTION_DATE=2023-02-07T08:38:33.165567+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-07T08:38:33.165567+00:00
[2023-02-07T09:39:07.793+0100] {__init__.py:117} DEBUG - Preparing lineage inlets and outlets
[2023-02-07T09:39:07.793+0100] {__init__.py:155} DEBUG - inlets: [], outlets: []
[2023-02-07T09:39:12.736+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.get_all_tweet_ids manual__2023-02-07T08:38:33.165567+00:00 [running]> from DB
[2023-02-07T09:39:12.740+0100] {base_job.py:240} DEBUG - [heartbeat]
[2023-02-07T09:39:17.786+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.get_all_tweet_ids manual__2023-02-07T08:38:33.165567+00:00 [running]> from DB
[2023-02-07T09:39:17.788+0100] {base_job.py:240} DEBUG - [heartbeat]
[2023-02-07T09:39:22.833+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.get_all_tweet_ids manual__2023-02-07T08:38:33.165567+00:00 [running]> from DB
[2023-02-07T09:39:22.835+0100] {base_job.py:240} DEBUG - [heartbeat]
[2023-02-07T09:39:27.875+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.get_all_tweet_ids manual__2023-02-07T08:38:33.165567+00:00 [running]> from DB
[2023-02-07T09:39:27.878+0100] {base_job.py:240} DEBUG - [heartbeat]
[2023-02-07T09:39:32.919+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.get_all_tweet_ids manual__2023-02-07T08:38:33.165567+00:00 [running]> from DB
[2023-02-07T09:39:32.922+0100] {base_job.py:240} DEBUG - [heartbeat]
[2023-02-07T09:39:37.893+0100] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/tr/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/tr/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/tr/airflow/dags/dagProcessusMetier.py", line 154, in get_all_tweet_ids
    for doc in docs:
  File "/home/tr/.local/lib/python3.10/site-packages/pymongo/cursor.py", line 1248, in next
    if len(self.__data) or self._refresh():
  File "/home/tr/.local/lib/python3.10/site-packages/pymongo/cursor.py", line 1139, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/tr/.local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1740, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/tr/.local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1685, in __start_session
    self._topology._check_implicit_session_support()
  File "/home/tr/.local/lib/python3.10/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/home/tr/.local/lib/python3.10/site-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/home/tr/.local/lib/python3.10/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: ac-7d3k6vb-shard-00-00.rs5oaul.mongodb.net:27017: timed out,ac-7d3k6vb-shard-00-01.rs5oaul.mongodb.net:27017: timed out,ac-7d3k6vb-shard-00-02.rs5oaul.mongodb.net:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 63e20e2b60f3525a4d6dc9db, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-7d3k6vb-shard-00-00.rs5oaul.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-7d3k6vb-shard-00-00.rs5oaul.mongodb.net:27017: timed out')>, <ServerDescription ('ac-7d3k6vb-shard-00-01.rs5oaul.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-7d3k6vb-shard-00-01.rs5oaul.mongodb.net:27017: timed out')>, <ServerDescription ('ac-7d3k6vb-shard-00-02.rs5oaul.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-7d3k6vb-shard-00-02.rs5oaul.mongodb.net:27017: timed out')>]>
[2023-02-07T09:39:37.895+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.get_all_tweet_ids manual__2023-02-07T08:38:33.165567+00:00 [running]> from DB
[2023-02-07T09:39:37.898+0100] {taskinstance.py:2241} DEBUG - Task Duration set to 30.214701
[2023-02-07T09:39:37.899+0100] {taskinstance.py:1329} DEBUG - Clearing next_method and next_kwargs.
[2023-02-07T09:39:37.899+0100] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=dagProcessusMetier, task_id=get_all_tweet_ids, execution_date=20230207T083833, start_date=20230207T083907, end_date=20230207T083937
[2023-02-07T09:39:37.926+0100] {cli_action_loggers.py:83} DEBUG - Calling callbacks: []
[2023-02-07T09:39:37.927+0100] {standard_task_runner.py:100} ERROR - Failed to execute job 2587 for task get_all_tweet_ids (ac-7d3k6vb-shard-00-00.rs5oaul.mongodb.net:27017: timed out,ac-7d3k6vb-shard-00-01.rs5oaul.mongodb.net:27017: timed out,ac-7d3k6vb-shard-00-02.rs5oaul.mongodb.net:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 63e20e2b60f3525a4d6dc9db, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-7d3k6vb-shard-00-00.rs5oaul.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-7d3k6vb-shard-00-00.rs5oaul.mongodb.net:27017: timed out')>, <ServerDescription ('ac-7d3k6vb-shard-00-01.rs5oaul.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-7d3k6vb-shard-00-01.rs5oaul.mongodb.net:27017: timed out')>, <ServerDescription ('ac-7d3k6vb-shard-00-02.rs5oaul.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-7d3k6vb-shard-00-02.rs5oaul.mongodb.net:27017: timed out')>]>; 2340)
[2023-02-07T09:39:37.946+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.get_all_tweet_ids manual__2023-02-07T08:38:33.165567+00:00 [running]> from DB
[2023-02-07T09:39:37.948+0100] {base_job.py:240} DEBUG - [heartbeat]
[2023-02-07T09:39:37.949+0100] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-07T09:39:37.957+0100] {dagrun.py:688} DEBUG - number of tis tasks for <DagRun dagProcessusMetier @ 2023-02-07 08:38:33.165567+00:00: manual__2023-02-07T08:38:33.165567+00:00, state:running, queued_at: 2023-02-07 08:38:33.178171+00:00. externally triggered: True>: 0 task(s)
[2023-02-07T09:39:37.957+0100] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
